Dax.Model.Extractor/TomExtractor.cs, Dax.Vpax/ExportVpax.cs, Dax.Vpax/ImportVpax.cs, Dax.Vpax/VpaxTools.cs, TestDaxModel/Program.cs
- Using TOM.Server instead of Microsoft.AnalysisServices.Server
- Using TOM.Database instead of Microsoft.AnalysisServices.Database
This PR will cause a breaking change in the VpaTools APIs, but from my tests all previously extracted VPAX files still work.
=> Using TOM = Microsoft.AnalysisServices.Tabular namespace

.azure/pipelines/ci.yml, src/Dax.Metadata/Model.cs, src/Dax.Model.Extractor/DmvExtractor.cs, src/Dax.Model.Extractor/TomExtractor.cs, src/Dax.Model.Extractor/Util.cs
- Fixed `ExtractorLibVersion` and `DaxModelLibVersion` (SEE notes in `Dax.Metadata.Extractor.Util.GetExtractorInfo`)
- Fixed duplicated hyphen-minus in `AssemblyInformationalVersion`
=> Fixed ExtractorLib and DaxModelLib version

src/Dax.Metadata/JsonConverters/DaxExpressionJsonConverter.cs, src/Dax.Metadata/JsonConverters/DaxNameJsonConverter.cs
Adds support for deserializing old VPAX files where these classes may have been serialized as `JObjects` instead of `string`
=> Fix DaxName and DaxExpression deserialization

src/Dax.Metadata/Column.cs, src/Dax.Metadata/Dax.Metadata.csproj, src/Dax.Model.Extractor/Dax.Model.Extractor.csproj, src/Dax.Model.Extractor/StatExtractor.cs, src/Dax.Model.Extractor/TomExtractor.cs, src/Dax.ViewVpaExport/Dax.ViewVpaExport.csproj, src/Dax.Vpax/Dax.Vpax.csproj, src/Dax.Vpax/ExportVpax.cs, src/Dax.Vpax/ImportVpax.cs, src/Dax.Vpax/VpaxFormat.cs, src/TestDaxModel/Program.cs, src/TestDaxModel/TestDaxModel.csproj, src/TestDaxWpf/TestDaxWpf.csproj, src/TestPowerBI/TestPowerBI.csproj, src/TestWpfPowerBI/TestWpfPowerBI.csproj
Based on this issue from DAX Studio https://github.com/DaxStudio/DaxStudio/issues/879  
I've extended the stats collector to generate correct queries when a column has GroupBy columns set.
I've also extended the vpax file format to generate a CompatibilityMode.txt file since if you save a file with a model.bim from a pbix file with field parameters it will not deserialize the bim file without knowing the compatibility mode, 
But I did also add a retry mechanism for backward compatibility so that if a vpax file has a bim in it the deserialize code will try all the different compatibility modes (PowerBI, AnalysisServices, Excel) if it gets a deserialization error.
=> Adding support for columns with GroupBy columns

src/Dax.Model.Extractor/TomExtractor.cs, src/TestDaxModel/Program.cs
I've added an additional overload to TomExtractor to allow a connection string to be passed in. This will allow for command line tools to generate VPAX files using SPN credentials against the PBI XMLA endpoint rather than relying on the interactive AAD login.
=> Adding ConnectionString option to TomExtractor

src/Dax.Model.Extractor/DmvExtractor.cs, src/TestDaxModel/Program.cs
It appears that the DynamicFormatStringID column in TMSCHEMA_MEASURES is not available UNLESS your model has at least one Dynamic formatstring. So I've swapped the order of the queries so that we check if we can run TMSCHEMA_FORMAT_STRING_DEFINITIONS and if it has any data before trying to map them to measures
=> Fixing error when model does not contain dynamic format strings

src/Dax.ViewModel/VpaRelationship.cs, src/TestDaxModel/Program.cs, src/TestDaxModel/TestDaxModel.csproj
This change will add the from/to column names for relationships to enable client tools to generate a DAX query to list RI Violations.
=> add from/to column names to VpaRelationship

src/Dax.Model.Extractor/Data/IDbConnectionExtensions.cs, src/Dax.Model.Extractor/Data/TomCommand.cs, src/Dax.Model.Extractor/Data/TomConnection.cs, src/Dax.Model.Extractor/DmvExtractor.cs, src/Dax.Model.Extractor/StatExtractor.cs, utils/TestDaxModel/Program.cs
`TomConnection` allows use an existing connection instead of letting VertiPaq Analyzer open its own connections to AS
=> Add TomConnection to allow use of an existing connection

src/Dax.Vpax/ExportVpax.cs, src/Dax.Vpax/Json/ShouldSerializeContractResolver.cs
- Use JSON `Formatting.None` and `DefaultValueHandling.Ignore`
- Add `ShouldSerializeContractResolver` to avoid empty array serialization
=> Reducing serialized JSON size

src/Dax.ViewVpaExport/Column.cs, src/Dax.ViewVpaExport/ColumnSegment.cs, src/Dax.ViewVpaExport/Measure.cs, src/Dax.ViewVpaExport/Table.cs, utils/TestDaxModel/TestDaxModel.csproj, utils/TestDaxWpf/TestDaxWpf.csproj, utils/TestPowerBI/TestPowerBI.csproj, utils/TestWpfPowerBI/TestWpfPowerBI.csproj
Fix a `NullReferenceException` error that occurs when when the `ViewVpa` model is extracted from a PowerPivot data model .
Other changes:
- Remove unnecessary `ToString()`
- Replace `ToString` with `Name` where a non-null `PartitionName` is expected
- TOM dependency version alignment in utils projects
=> Fix NullReferenceException on ViewVpa export

src/Dax.Metadata/Column.cs, src/Dax.Metadata/Partition.cs, src/Dax.Metadata/Table.cs, src/Dax.Model.Extractor/DmvExtractor.cs, src/Dax.Model.Extractor/StatExtractor.cs, src/Dax.Model.Extractor/TomExtractor.cs, src/Dax.Model.Extractor/Util.cs, src/Directory.Packages.props, utils/TestDaxModel/Program.cs, utils/TestDaxModel/TestDaxModel.csproj, utils/TestDaxWpf/MainWindow.xaml.cs, utils/TestDaxWpf/TestDaxWpf.csproj, utils/TestPowerBI/TestPowerBI.csproj, utils/TestWpfPowerBI/MainWindow.xaml.cs, utils/TestWpfPowerBI/Model/TreeViewPbiItems.cs, utils/TestWpfPowerBI/PowerBI/MetadataTools.cs, utils/TestWpfPowerBI/TestWpfPowerBI.csproj, utils/TestWpfPowerBI/Views/PbiMetadataTreeView.xaml.cs
Added 3 different modes for direct lake models so that we do not always force all columns to be transcoded into memory.
* **ResidentOnly** - only run the distinctcount queries on columns that are current resident in memory
* **Referenced** - run distinctcount queries on columns that are referenced by measures or relationships. This should provide the minimum information required for performance analysis of measures and for tools like DAX Optimizer.
* **Full** - run distinctcount queries on all columns
I've added this option since the default behaviour at the moment is the same as **Full** and this can be detrimental to large models. It can take longer than necessary and potentially may still not produce the desired result since as we cycle through all the columns it could force some of …
=> Adding Directlake options for collecting metrics

src/Dax.Model.Extractor/StatExtractor.cs, src/Dax.Model.Extractor/TomExtractor.cs
- Re-run `DmvExtractor` only if `readStatisticsFromData` is enabled
- Add `DmvExtractor` re-run to `GetDaxModel` overload
- Remove `analyzeDirectQuery` filter when retrieving referential integrity violations
=> Minor fixes for DirectLake metric collection

src/Dax.Model.Extractor/Data/IDbConnectionExtensions.cs, src/Dax.Model.Extractor/Data/TomConnection.cs
After upgrading to 1.5.0, Tabular Editor 3 is not able to collect VertiPaq Analyzer stats, because we use the TomConnection wrapper for an existing connection created using AMO/TOM.
In 1.5.0, the connection's State property is read inside the DmvExtractor. However, the State property was not mplemented for the TomConnection wrapper. This PR fixes that.
=> Fix for TomConnection NotImplementedException

src/Dax.Model.Extractor/StatExtractor.cs, src/Dax.Model.Extractor/TomExtractor.cs
This commit introduces a new `int columnBatchSize` parameter to control the number of rows processed at a time during column statistics analysis. It also adds the `StatExtractor.DefaultColumnBatchSize` constant to define the default number of rows processed when no value is provided.
=> Add batch size control for column statistics analysis

src/Dax.Model.Extractor/StatExtractor.cs
Added a check to ensure `columnBatchSize` is greater than zero in the `UpdateStatisticsModel` method of `StatExtractor.cs`
=> Add columnBatchSize validation to UpdateStatisticsModel method

src/Dax.Vpax.CLI/Commands/ExportCommand.cs, src/Dax.Vpax.CLI/Commands/ExportCommandHandler.cs, src/Dax.Vpax.CLI/Commands/ExportCommandOptions.cs, src/Dax.Vpax.CLI/Dax.Vpax.CLI.csproj, src/Dax.Vpax.CLI/version.json
Adds advanced extract option:
`--direct-query-mode` : [Direct Query extraction mode](https://github.com/sql-bi/VertiPaq-Analyzer/blob/8bd92126b3bbddfc1ec6c82c51d2d00c12ee2d3f/src/Dax.Metadata/ExtractorProperties.cs#L51-L62)
`--direct-lake-mode` : [Direct Lake extraction mode](https://github.com/sql-bi/VertiPaq-Analyzer/blob/8bd92126b3bbddfc1ec6c82c51d2d00c12ee2d3f/src/Dax.Metadata/ExtractorProperties.cs#L30C1-L49C2).
`--column-batch-size`: Number of rows processed at a time during column statistics analysis
=> [cli] Bump VPAX 1.7.0, add advanced export options

src/Dax.Model.Extractor/StatExtractor.cs
This commit fixes an issue where the cardinality of a column would result in zero if the column had `GroupByColumns` specified and `IsAvailableInMDX=false`. This occurred because statistics for these columns are not available in the DMV `$SYSTEM.DISCOVER_STORAGE_TABLES` (see `WHERE LEFT(TABLE_ID, 2) = 'H$'` in PopulateColumnsCardinality).
=> Extend column statistics analysis to include columns with GroupByColumns

src/Directory.Packages.props
Updated the System.IO.Packaging version from fixed 6.0.0 to a range [6.0.0, 7.0.0) preventing major version upgrades
=> Pin System.IO.Packaging to version range [6.0.0, 7.0.0)

src/Dax.Model.Extractor/StatExtractor.cs
This update resolves an issue in StatExtractor where an error occurred during the extraction of relationship statistics when one of the columns in the relationship was part of a composite key (GroupByColumns). The error message was: "Column [] is part of composite key, but not all columns of the composite key are included in the expression or its dependent expression." This fix applies only to models with a compatibility level of 1200 or higher, as GroupByColumns is not available in levels 1100 and 1103.
=> Fix to support composite key columns (GroupByColumns) in StatExtractor

src/Dax.Metadata/Table.cs, src/Dax.Model.Extractor/TomExtractor.cs, src/Dax.ViewVpaExport/Table.cs
Add `Table.DefaultDetailRowsExpression` property to support extraction for table detail rows expression.
The property has been added to both `Dax.Model.Table` and `Dax.ViewVpaExport.Table`.
Bumped `Dax.Model.Version` to 1.6.0
=> Add Table.DefaultDetailRowsExpression property, bump model version 1.6.0

src/Dax.Model.Extractor/DmvExtractor.cs
Enhanced DmvExtractor.cs by adding conditional logic for RowsCount and ColumnCardinality, ensuring they are assigned only if their current values are zero. This prevents overwriting the more precise values extracted by StatsExtractor with potentially less accurate values from DmvExtractor when DmvExtractor is called after StatsExtractor. Currently, this may happen for models with DirectLake partitions and DirectLakeExtractionMode > ResidentOnly (see GetDaxModel() implementation)
=> Enhance DmvExtractor to preserve RowsCount/ColumnCardinality stats for DL models

src/Dax.Model.Extractor/DmvExtractor.cs
This pull request introduces several changes to the `DmvExtractor.cs` file, specifically addressing the handling of null values for data extracted by the `DmvExtractor` related to the following DMVs: `DISCOVER_STORAGE_TABLES`, `DISCOVER_STORAGE_TABLE_COLUMNS`, and `DISCOVER_STORAGE_TABLE_COLUMN_SEGMENTS`.
In DirectLake mode, these DMVs may return null values, which are now replaced with zero.
Affected VPAX Properties:
- `Table.RowsCount`
- `Column.DictionarySize`
- `ColumnSegment.SegmentNumber`
- `ColumnSegment.SegmentRows`
- `ColumnSegment.UsedSize`
- `ColumnHierarchy.SegmentNumber`
- `ColumnHierarchy.UsedSize`
_Handling Null SEGMENT_NUMBER for Column Segments and Hierarchies_:
In cases where SEGMENT_NUMBER is null, a unique identifier is assigned based on the segment's position within …
=> Handle null values in DmvExtractor for DirectLake partitions

src/Directory.Packages.props
Updated the `Microsoft.AnalysisServices` and `Microsoft.AnalysisServices.AdomdClient` package versions from `19.86.6` to `19.90.0`
=> Bump Microsoft.AnalysisServices deps from 19.86.6 to 19.90.0

src/Dax.Metadata/CalculationGroup.cs, src/Dax.Metadata/CalculationItem.cs, src/Dax.Metadata/Column.cs, src/Dax.Metadata/ColumnHierarchy.cs, src/Dax.Metadata/ColumnSegment.cs, src/Dax.Metadata/Measure.cs, src/Dax.Metadata/Model.cs, src/Dax.Metadata/Partition.cs, src/Dax.Metadata/Role.cs, src/Dax.Metadata/Table.cs, src/Dax.Metadata/TablePermission.cs, src/Dax.Metadata/UserHierarchy.cs
Parent navigation properties (e.g., `column.Table`) are now excluded from JSON serialization. These properties are used by child entities to access their parent objects, but they are automatically reassigned during deserialization via the `OnDeserialized` attribute/ method. Therefore, including them in the JSON is redundant. By excluding these references, we also reduce the overall JSON size and avoid generating unnecessary object $ref entries.
=> Exclude parent entity $ref from JSON serialization, fix null CalculationGroup.Table after deserialization

src/Dax.Metadata/CalculationGroup.cs, src/Dax.Metadata/Model.cs, src/Dax.Model.Extractor/TomExtractor.cs, src/Dax.ViewVpaExport/CalculationGroup.cs, src/Dax.ViewVpaExport/Model.cs
This pull request introduces support for additional expression types within calculation groups and updates the DAX model version. The key changes include the addition of new properties for handling selection expressions in calculation groups, updates to the model extractor to populate these properties, and the introduction of a new `CalculationGroup` class in the `Dax.ViewVpaExport` namespace to expose these properties.
* [`src/Dax.Metadata/CalculationGroup.cs`](diffhunk://#diff-0046c13686610ccc5dd3cb6b40c1a9b0e68363550a55b9a82632c6fa63e728c1R26-R33): Added new properties to `CalculationGroup` for `MultipleOrEmptySelectionExpression`, `MultipleOrEmptySelectionFormatStringExpression`, `NoSelectionExpression`, and `NoSelectionFormatStringExpression`. These properties will store the …
=> Support `CalculationGroup.MultipleOrEmpty` and `NoSelection` expressions. Bump model version to 1.8.0

src/Dax.Metadata/Table.cs
The `[JsonIgnore]` attribute was removed from the `Model` property in the `Dax.Metadata` namespace. Comments were added to explain the history of this change, noting that the attribute was initially introduced in VAPX 1.11-preview2 but was commented out to avoid breaking changes during deserialization with earlier library versions. The comments also reference a related pull request and suggest the possibility of uncommenting the attribute in future versions.
=> Fixup - remove JsonIgnore from Metadata.Table.Model property

src/Dax.Metadata/CalculationGroup.cs, src/Dax.Model.Extractor/TomExtractor.cs, src/Dax.ViewVpaExport/CalculationGroup.cs
This pull request introduces enhancements to the `CalculationGroup` class and related methods to support descriptions for `MultipleOrEmptySelectionExpression` and `NoSelectionExpression`DAX expressions. 
* [`src/Dax.Metadata/CalculationGroup.cs`](diffhunk://#diff-0046c13686610ccc5dd3cb6b40c1a9b0e68363550a55b9a82632c6fa63e728c1R26-R37): Added new properties to the `CalculationGroup` class to store descriptions for `MultipleOrEmptySelectionExpression`, `NoSelectionExpression`, and the overall `CalculationGroup`. 
* [`src/Dax.Model.Extractor/TomExtractor.cs`](diffhunk://#diff-d56b1e47e7b80000e9032f424d11e18448b2118ddee94a3150e3c1f790905decR185-R190): Updated the `AddTable` method to populate the new description properties (`Description`, `MultipleOrEmptySelectionExpressionDescription`, and …
=> Add Description property for CalculationGroup and Selection expressions

src/Dax.Vpax.CLI/Dax.Vpax.CLI.csproj
This pull request updates the package dependencies in the `Dax.Vpax.CLI` project to use newer versions of the referenced libraries.
Dependency updates:
* Updated `Dax.Model.Extractor`, `Dax.ViewModel`, and `Dax.Vpax` package references from version `1.11.0-preview3` to `1.11.0-preview4` in `src/Dax.Vpax.CLI/Dax.Vpax.CLI.csproj`.
=> Bump VPAX version 1.11.0-preview4

src/Dax.Model.Extractor/DmvExtractor.cs
This reverts commit ca747413b015e1650660ed1cc569dcc11f698b5e PR #196. Zero is now returned instead of null values, making the previous fix unnecessary.
=> Revert "Handle null values in DmvExtractor for DirectLake partitions"

src/Dax.Metadata/Calendar.cs, src/Dax.Metadata/CalendarColumnGroup.cs, src/Dax.Metadata/JsonConverters/CalendarColumnGroupCustomCreationConverter.cs, src/Dax.Metadata/Model.cs, src/Dax.Metadata/Table.cs, src/Dax.Metadata/TimeUnit.cs, src/Dax.Model.Extractor/TomExtractor.cs
This pull request introduces support for `Calendar` feature, enabling tables to have associated calendar metadata and supporting advanced time-based grouping and associations. The implementation includes new domain classes, JSON serialization/deserialization logic, and integration into the model extraction process.
**New Calendar feature and model integration:**
* Added new `Calendar` domain model (`Calendar`, `CalendarColumnGroup`, `TimeRelatedColumnGroup`, `TimeUnitColumnAssociation`) to represent calendar metadata, including time-based column groups and associations. (`src/Dax.Metadata/Calendar.cs`, `src/Dax.Metadata/CalendarColumnGroup.cs`, [[1]](diffhunk://#diff-0ed76089056a27e2cad07364b5a27e1113f7ca4d94403f78c0ab3cdf6acf8f78R1-R27) …
=> Add `Dax.Metadata.Calendar`, bump model version to 1.9.0
